### ISSUE TITLE
Add Open Source License

### ISSUE THREAD

**Issue by snipem** [e13mort/STF-gradle-plugin#5]
Please add a License (for example Apache 2.0) to the project. We cannot use the library without an open source license explicitly stated.

Feel free to close this issue without note if you want to keep it proprietary.

**Comment by e13mort** [comment]
Hello. Thanks for the issue. I fully understand your situation and gonna add the Apache 2.0 license in a couple of days.
In order to speed up the process you could submit a pull request with the license.

**Comment by e13mort** [comment]
Thanks for MR. Closing the issue.
