### ISSUE TITLE
Migrate from jCenter

### ISSUE THREAD

**Issue by e13mort** [e13mort/STF-gradle-plugin#7]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by realdadfish** [comment]
Whats the status of this? The jcenter shutdown is nearing... :(

**Comment by e13mort** [comment]
> Whats the status of this? The jcenter shutdown is nearing... :(

Hi. Gonna solve this in a couple of days I hope

**Comment by e13mort** [comment]
UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

So it's not urgent anymore. Will migrate for a next release.

**Comment by e13mort** [comment]
Migrated to jitpack for version 0.4.0
